#!/bin/bash
#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# make us exit on a failure
set -e

./default-build "$@"

if [[ $@ != *"--jvm"* ]]; then
  # Change the generated dex file to have a v36 magic number if it is version 35
  if test -f classes.dex && head -c 7 classes.dex | grep -q 035; then
    # place ascii value '037' into the classes.dex file starting at byte 4.
    printf '037' | dd status=none conv=notrunc of=classes.dex bs=1 seek=4 count=3
    rm -f $TEST_NAME.jar
    zip $TEST_NAME.jar classes.dex
  fi
fi
