#!/bin/bash
#
# Copyright 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This checker test is incompatible with jack bytecode output,
# so force it to use javac/dx.
export USE_JACK=false
# Also disable desugar because it is missing in jack platform builds.
export DESUGAR=false

# See b/65168732
export USE_D8=false

./default-build "$@"
