#!/bin/bash
#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# make us exit on a failure
set -e

# Should we compile with Java source code. By default we will use Smali.
USES_JAVA_SOURCE="false"
if [[ $@ == *"--jvm"* ]]; then
  USES_JAVA_SOURCE="true"
elif [[ "$USE_JACK" == "true" ]]; then
  if $JACK -D jack.java.source.version=1.8 -D jack.android.min-api-level=24 2>/dev/null; then
    USES_JAVA_SOURCE="true"
  else
    echo "WARNING: Cannot use jack because it does not support JLS 1.8. Falling back to smali" >&2
  fi
fi

if [[ "$USES_JAVA_SOURCE" == "true" ]]; then
  # Build the Java files
  mkdir -p src
  mkdir -p src2
  ./util-src/generate_java.py ./src2 ./src ./expected.txt
else
  # Generate the smali files and expected.txt or fail
  mkdir -p smali
  ./util-src/generate_smali.py ./smali ./expected.txt
fi

./default-build "$@" --experimental default-methods
