#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ensure flags includes prebuild and relocate. It doesn't make sense unless we
# have a oat file we want to relocate.
flags="$@"

# This test is supposed to test with oat files. Make sure that the no-prebuild flag isn't set,
# or complain.
# Note: prebuild is the default.
if [[ "${flags}" == *--no-prebuild* ]] ; then
  echo "Test 117-nopatchoat is not intended to run in no-prebuild mode."
  exit 1
fi

# This test is supposed to test relocation. Make sure that the no-relocate flag isn't set,
# or complain.
# Note: relocate is the default.
if [[ "${flags}" == *--no-relocate* ]] ; then
  echo "Test 117-nopatchoat is not intended to run in no-relocate mode."
  exit 1
fi

# Make sure we can run without relocation
echo "Run without dex2oat/patchoat"
${RUN} ${flags} --runtime-option -Xnodex2oat
return_status1=$?

# Make sure we can run with the oat file.
echo "Run with dexoat/patchoat"
${RUN} ${flags} --runtime-option -Xdex2oat
return_status2=$?

# Make sure we can run with the default settings.
echo "Run default"
${RUN} ${flags}
return_status3=$?

# Make sure we don't silently ignore an early failure.
(exit $return_status1) && (exit $return_status2) && (exit $return_status3)
