#!/bin/bash
#
# Copyright (C) 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Jack has a different set of bytecode offsets/method IDs in the expected.txt
if [[ "$USE_JACK" == true ]]; then
  patch -p0 expected.txt < expected_jack.diff
fi

./default-check "$@"
if [[ "$?" == "0" ]]; then
  exit 0;
fi

# We cannot always correctly determine if D8 was used because of (b/68406220).
# So we are just going to try to see it matches the expect output of D8 no
# matter what.
patch -p0 expected.txt < expected_d8.diff

./default-check "$@"
