#!/bin/bash
#
# Copyright (C) 2012 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

mkdir classes

# android.test.anno.MissingAnnotation is available at compile time...
${JAVAC} -d classes `find src -name '*.java'`
# overwrite RenamedEnum
${JAVAC} -d classes `find src2 -name '*.java'`

# ...but not at run time.
rm 'classes/android/test/anno/MissingAnnotation.class'
rm 'classes/android/test/anno/ClassWithInnerAnnotationClass$MissingInnerAnnotationClass.class'

if [ ${USE_JACK} = "true" ]; then
  jar cf classes.jill.jar -C classes .
  # Jack needs to emit annotations with CLASS retention.
  ${JACK} -D jack.dex.annotation.class-retention=true --import classes.jill.jar --output-dex .
else
  if [ ${NEED_DEX} = "true" ]; then
    ${DX} -JXmx256m --debug --dex --output=classes.dex classes
  fi
fi

if [ ${NEED_DEX} = "true" ]; then
  zip $TEST_NAME.jar classes.dex
fi
