#!/bin/bash
#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "$#" -ne "2" ]; then
  echo "Usage: ./extract_embedded_java.sh smali_dir java_dir"
  exit 1
fi

# Check the input and output are directories
[[ -d "$1" ]] || exit 1
[[ -d "$2" ]] || exit 1

# For every file which has the file extension smali, set $f to be the name without
# .smali and then:
for f in `find "$1" -type f -name "*.smali" | xargs -n 1 -P 0 -i basename -s .smali \{\}`; do
  # remove all lines except those starting with '# ', remove the '#' then print
  # it to a file ${name}.java. Do this concurrently.
  grep "^# " "$1/${f}.smali" | sed "s:# ::" > "${2}/${f}.java" &
done

# wait for all the files to be written
wait
