#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Do not compare numbers, so replace numbers with 'N'.
# Remove all messages relating to failing to allocate a java-peer for the
# shutdown thread. This can occasionally happen with this test but it is not
# something we really need to worry about here.
sed '-es/[0-9][0-9]*/N/g' "$2" \
  | sed "/Exception creating thread peer:/,+3d" \
  | diff --strip-trailing-cr -q "$1" - >/dev/null
