#!/bin/bash
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# We are testing the redefinition of compiled code but with jvmti we only allow
# jitted compiled code so always add the --jit argument.
if [[ "$@" == *"--jit"* ]]; then
  other_args=""
else
  other_args="--jit"
fi
./default-run "$@" ${other_args} \
                   --jvmti
