#!/bin/bash
#
# Copyright (C) 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

mkdir classes
# Only keep the source name, to make sure we do remove it in the stack trace
# when there is no line number mapping.
${JAVAC} -g:source -source 7 -target 7 -d classes `find src -name '*.java'`
${DX} --dex --output=classes.dex classes
zip $TEST_NAME.jar classes.dex
