#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Only keep the lines we're interested in.
sed -s '/^.*: oat file has dex code, but APK has uncompressed dex code\|Hello World/!d' "$2" > "$2.tmp"

# Remove part of message containing filename.
sed -s 's/^.*: //' "$2.tmp" > "$2.tmp2"

diff --strip-trailing-cr -q "$1" "$2.tmp2" >/dev/null
