#!/bin/bash
#
# Copyright (C) 2018 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The number of paused background threads (and therefore InterruptedExceptions)
# can change so we will just delete their lines from the log.

# Pure virtual function can be printed because sudden exits are not really
# supported. It is an error message but the test is to make sure that we exit
# with the right exit code.
cat "$2" \
  | sed "/Pure virtual function called!/d" \
  | diff --strip-trailing-cr -q "$1" - >/dev/null
