#!/bin/bash
#
# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

# Write out a bunch of source files.
gcc -Wall -Werror -o classes-gen classes-gen.c
./classes-gen

if [ ${USE_JACK} = "true" ]; then
  # Use the default Jack commands
  ./default-build
else
  mkdir classes
  ${JAVAC} -d classes src/*.java

  # dx needs more memory for that test so do not pass Xmx option here.
  if [ ${NEED_DEX} = "true" ]; then
    ${DX} --debug --dex --output=classes.dex classes
    zip $TEST_NAME.jar classes.dex
  fi
fi
