#!/bin/bash
#
# Copyright (C) 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

# The test relies on DEX file produced by javac+dx so keep building with them for now
# (see b/19467889)
mkdir classes
${JAVAC} -d classes `find src -name '*.java'`
${DX} -JXmx256m --debug --dex --dump-to=classes.lst --output=classes.dex \
  --dump-width=1000 ${DX_FLAGS} classes
zip $TEST_NAME.jar classes.dex
