#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ensure flags includes prebuild.
flags="$@"
if [[ "${flags}" == *--no-prebuild* ]] ; then
  echo "Test 147-stripped-dex-fallback is not intended to run in no-prebuild mode."
  exit 1
fi

${RUN} ${flags} --strip-dex --runtime-option -Xnodex2oat
